export const RESERVATION_SELECT_QUERY = `
  id,
  reservation_id,
  created_at,
  main_client_name,
  booking_platform,
  total_amount,
  total_cost,
  reservation_fee,
  deposit,
  author,
  author_email,
  is_confirmation_published,
  content,
  trip_type,
  travel_category,
  start_date,
  end_date,
  nights,
  days,
  clients!clients_reservation_id_fkey (*),
  flights!flights_reservation_id_fkey (*),
  hotels!hotels_reservation_id_fkey (*),
  tours!tours_reservation_id_fkey (*),
  rental_cars!rental_cars_reservation_id_fkey (*),
  insurances!insurances_reservation_id_fkey (*)
`;
