export const DIAMOND_HEAD_HIKING = {
  arrival_location:
    '<p>쉐라톤 와이키키 입구 - 벨보이 있는 곳</p><p></p><p><span class="node-image"><span class="image-component"><img src="https://hpwrnhxgnawyfmhwqqsm.supabase.co/storage/v1/object/public/location-images/reservations/20260529-JH001/location/a0cdec72-76d1-4847-a236-44ab4a543519.png" alt="쉐라톤 입구.png" title="" width="null" height="null" style="max-width: nullpx" data-keep-ratio="true" class=""></span></span></p>',
  delivery_notes:
    '<ul><li><p><span style="color: rgb(59, 130, 246);"><strong>별도 첨부드린 다이아몬드헤드 입장권(인쇄본) 필수 지참하셔야 합니다.</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>해당 입장권의 QR코드는 1회용으로 반드시 입장하실 때 스캔하셔야 합니다. (미리 스캔 시 입장/환불 불가)</strong></span></p></li><li><p><strong>택시 하차 전 기사님과 호텔 복귀편 택시 미팅 시간 직접 조율하시기 바랍니다.</strong></p></li><li><p>(하이킹 왕복 평균 소요시간은 대략 1시간30분~2시간 정도 입니다.)</p></li></ul><p></p>',
  guide_notes:
    '<ul><li><p>본 바우처를 캡쳐 또는 출력하여 가져가시기 바랍니다. 바우처 미 지참시 진행이 불가합니다.</p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>별도 첨부드린 다이아몬드헤드 입장권은 인쇄하여 필수 지참하셔야 합니다. </strong></span><span style="color: rgb(23, 23, 23);">해당 입장권의 QR코드는 1회용으로 반드시 입장하실 때 스캔하셔야 합니다. (미리 스캔 시 입장/환불 불가)</span></p></li><li><p>준비물 : 편안한 복장&amp;신발(운동화), 생수, 선크림, 선글라스 등 개인물품 (짐은 최소한으로 준비하시기 바랍니다.) 추위를 타신다면 가벼운 겉옷 지참 권장드립니다.</p></li><li><p>당일 교통사정에 의해 픽업시간이 5~10분 정도 지연되더라도 정해진 픽업장소를 이탈하지 마시고, 조인하와이 현지 연락처로 연락주시기 바랍니다.</p></li><li><p>개인행동으로 인한 행사 불참 시에는 별도의 연락없이 진행되며 전액 환불 불가합니다.</p></li><li><p>바우처에 기재된 장소를 모르실 경우 현지 조인하와이로 문의하여 안내 받으시기 바랍니다.</p></li><li><p>택시 하차 전 기사님과 호텔 복귀편 택시 미팅 시간 직접 조율하시기 바랍니다. (하이킹 총 소요시간 대략 1시간30분~2시간)</p></li><li><p>정해진 일정 외 장소 방문은 불가합니다.</p></li><li><p>카시트/부스터는 제공되지 않으며 장착도 불가합니다.</p></li><li><p><span style="color: rgb(239, 68, 68);"><strong>취소나 변경이 불가합니다.</strong></span></p></li></ul><p></p>'
};

export const STAR_OF_HONOLULU_3STAR_NO_PICKUP = {
  arrival_location:
    '<p><strong>Star of Honolulu 라고 써있는 배 입구 쪽에서 직원에게 바우처 제시 부탁드립니다.</strong></p><p></p><p>ALOHA TOWER MARKETPLACE Pier 8 또는</p><p>1 ALOHA TOWER DRIVE HONOLULU, HI 96813 를 네비게이션에 검색하시면 됩니다.</p>',
  guide_notes:
    '<ul><li><p><span style="color: rgb(59, 130, 246);"><strong>본 바우처를 출력 또는 핸드폰 캡쳐본으로 제시해주셔야 합니다. 바우처 미지참 시 투어 진행/환불 불가합니다.</strong></span></p></li><li><p>체크인 시간 불이행으로 인한 행사 불참 시 별도의 연락없이 진행되며 전액 환불 불가합니다.</p></li><li><p>바우처에 기재된 장소를 모르실 경우 현지 조인하와이로 사전 문의하셔서 안내 받으시기 바랍니다.</p></li><li><p>별도 드레스 코드는 없으나 남성 : 소매없는 나시, 쪼리 / 여성 : 쪼리 착용 시 투어 참여/환불 불가합니다.</p></li><li><p>저녁에는 쌀쌀해지므로 겉옷 지참 권장드립니다.</p></li><li><p>현지 사정으로 인해 투어 일정이 예고없이 변경되거나 취소될 수 있습니다.</p></li></ul><p></p>'
};

export const STAR_OF_HONOLULU_3STAR_PICKUP = {
  arrival_location:
    '<p><strong>SHERATON WAIKIKI 호텔 - ALOHA LANDING (알로하 랜딩)</strong></p><p></p><p><span class="node-image"><span class="image-component"><img src="https://hpwrnhxgnawyfmhwqqsm.supabase.co/storage/v1/object/public/location-images/reservations/20260529-JH001/location/37c83481-8a80-428d-8e74-e80598b26f43.jpg" alt="SHERATON WAIKIKI 호텔 - ALOHA LANDING (알로하 랜딩) 1.jpg" title="" width="459.795166015625" height="217.69793701171875" style="max-width: 459.795166015625px" data-keep-ratio="true" class=""></span></span></p>',
  delivery_notes:
    "<ul><li><p><strong>차량에 'ROYAL STAR'라고 적혀있습니다.</strong></p></li><li><p>흰색 상의 뒷면에 'STAR OF HONOLULU'라고 적혀있는 옷을 입은 직원이 성함호명.</p></li><li><p>외국인 직원의 발음이 부정확할 수 있으므로 먼저 확인하신 후 차량 탑승하시기 바랍니다.</p></li></ul>",
  guide_notes:
    '<ul><li><p><span style="color: rgb(59, 130, 246);"><strong>본 바우처를 출력 또는 핸드폰 캡쳐본으로 제시해주셔야 합니다. 바우처 미지참 시 투어 진행/환불 불가합니다.</strong></span></p></li><li><p>픽업시간 보다 10분 일찍 픽업장소에서 대기하여 주시기 바랍니다.</p></li><li><p>픽업시간이 5분 정도 지연될 경우 픽업장소를 이탈하지 마시고, 조인하와이 현지 연락처로 연락주시기 바랍니다.</p></li><li><p>픽업시간 지연 시 연락을 주시지 않아 픽업이 안되었을 경우 취소 및 환불이 불가합니다.</p></li><li><p>시간 불이행으로 인한 행사 불참 시에는 별도의 연락은 드리지 않으며, 전액 환불 불가합니다.</p></li><li><p>바우처에 기재된 장소를 모르실 경우 현지 조인하와이로 문의하여 안내 받으시기 바랍니다.</p></li><li><p>별도 드레스 코드는 없으나 남성 : 소매없는 나시, 쪼리 / 여성 : 쪼리 착용 시 투어 참여/환불 불가합니다.</p></li><li><p>저녁에는 쌀쌀해지므로 겉옷 지참 권장드립니다.</p></li><li><p>현지 사정으로 인해 투어 일정이 예고없이 변경되거나 취소될 수 있습니다.</p></li></ul>'
};

export const ONE_DAY_TOUR = {
  arrival_location:
    '<p><span style="color: rgb(23, 23, 23);"><strong>평균 06:20 AM ~ 07:20 AM (투어 전 날 정확한 픽업 시간 안내드립니다.)</strong></span></p><p></p><p>SHERATON WAIKIKI 호텔 - 고객 전용 주차장 건물 입구 Donho Lane (돈호레인)</p><p><span class="node-image"><span class="image-component"><img src="https://hpwrnhxgnawyfmhwqqsm.supabase.co/storage/v1/object/public/location-images/reservations/20260529-JH001/location/72d604c5-553a-49c7-ad6d-2ae44b7a77c0.jpg" alt="SHERATON WAIKIKI 호텔 - 고객 전용 주차장 건물 입구 Donho Lane (돈호레인) 1.jpg" title="" width="433.1458435058594" height="214.78125" style="max-width: 433.1458435058594px" data-keep-ratio="true" class=""></span></span></p>',
  delivery_notes:
    '<ul><li><p>카카오톡 설정 - 친구 카테고리에서<span style="color: rgb(239, 68, 68);"><strong> \'전화번호로 친구 추가 허용\'을 활성화 </strong></span>해주시기 바랍니다. &nbsp;</p></li><li><p>17시까지 카톡을 못 받으셨을 경우 <span style="color: rgb(59, 130, 246);"><strong>현지 연락처로 먼저 연락</strong></span> 부탁드립니다. (카톡ID : joinhawaiiusa / 연락처 : 1-808-772-2691 )</p></li></ul>',
  guide_notes:
    '<ul><li><p><span style="color: rgb(59, 130, 246);"><strong>픽업시간은 투어 전날 오후 5시 이전에 별도로 안내드립니다. 안내를 못받으셨다면 조인하와이 현지 연락처로 연락주시기 바랍니다.</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>본 바우처와 모든 분들의 여권을 준비하여 가시기 바랍니다. 미 지참시 투어 참여/환불 불가합니다.</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>가이드팁 1인당 $10, 점심 팁 1인당 $3 별도로 준비하여 주시기 바랍니다.</strong></span></p></li><li><p>겉옷 지참 부탁드립니다.</p></li><li><p>픽업시간 보다 10분 일찍 픽업장소에서 대기하여 주시기 바랍니다.</p></li><li><p>픽업시간이 5분 정도 지연될 경우 픽업장소를 이탈하지 마시고, 조인하와이 현지 연락처로 연락주시기 바랍니다.</p></li><li><p>픽업시간 지연 시 연락을 주시지 않아 픽업이 안되었을 경우 취소 및 환불이 불가합니다.</p></li><li><p>픽업시간 불이행으로 인한 행사 불참 시에는 별도의 연락은 드리지 않습니다.</p></li><li><p>멀미약은 필요 시 개별적으로 사전 복용 하셔야 하며, 멀미로 인한 환불은 불가합니다.</p></li><li><p>취소, 변경, 환불이 불가한 투어입니다.</p></li></ul>'
};

export const KUALOA_RANCH_UTV_RAPTOR_ADVENTURE_NO_PICKUP = {
  arrival_location:
    '<p><strong>쿠알로아 랜치 </strong><span style="color: rgb(59, 130, 246);"><strong>티켓 오피스</strong></span><strong>에 가셔서 </strong><span style="color: rgb(59, 130, 246);"><strong>바우처와 여권 제시</strong></span><strong> 부탁드립니다.</strong></p><p></p><p>티켓 오피스에서 체크인 하시고 인쇄 탑승권 또는 모바일 탑승권을 수령하신 후 안내받으신 투어 장소로 이동하시면 됩니다.</p><p>투어 장소에 있는 <strong>가이드에게</strong> 다시 한 번 <strong>체크인</strong> 하시면 됩니다.</p><p></p><p><strong>[GPS, 구글 지도 입력] Kualoa Ranch Ticket Office</strong></p><p><strong>[Kualoa Ranch 주소] 49-560 Kamehameha Hwy, Kaneohe, HI 96744</strong></p>',
  delivery_notes:
    '<ul><li><p>투어 참여하시는 <strong>모든 분들은 쿠알로아랜치에서 제공하는 위 링크 </strong><span style="color: rgb(239, 68, 68);"><strong>면책 동의서 제출</strong></span>하셔야 참여 가능합니다.</p></li><li><p>위 링크 전체를 복사하여 인터넷 창에 붙여넣기 하신 후 \'Sign waivers\'를 클릭하시고 모든 인원의 정보를 기입하시면 됩니다.</p></li><li><p>동의서는 미리 등록하셔도 되고, 늦어도 체크인 하시기 전까지 제출하셔야 합니다.<span style="color: rgb(239, 68, 68);"> <strong>(미제출 시 투어 참여, 환불 불가)</strong></span></p></li></ul>',
  guide_notes:
    '<ul><li><p>본 바우처를 출력 또는 캡쳐하여 가져가시기 바랍니다. 바우처 미 지참시 진행이 불가합니다.</p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>준비물 : 바우처(캡처본), 대표 예약자의 여권(지참 또는 사진촬영본 가능), UTV 운전자분의 국제운전면허증 실물 지참</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>바우처와 여권은 예약자명과 일치하여야 하며 여권은 본인 확인을 위해 사진이 있는 전체 페이지를 제시해주셔야 합니다.</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>UTV 운전자는 만 21세 이상이여야 하며, 운전자 명의 국제운전면허증 지참하셔야 합니다. 준비물 미지참 시 투어 참여 불가하며, 전액 환불 불가합니다.</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>투어 참여에 적절한 편안한 복장 &amp; 운동화 착용과 햇빛(자외선)이 강할 수 있어 필요 시 썬글라스와 썬크림 지참 권장드립니다.</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>위에 기재된 체크인 시간에 늦지 않게 도착하시기 바랍니다. (쿠알로아랜치 규정 상 프로그램 시간 45분 전까지 체크인 하셔야 합니다.) </strong></span>투어 당일 렌터카 픽업하시는 분들께선 렌터카 픽업이 지연될 경우 쿠알로아 체크인 시간까지 도착 못하실 수 있습니다. 체크인 시간 불이행으로 인한 행사 불참 시 별도의 연락없이 진행되며 전액 환불 불가합니다.</p></li><li><p>투어 참여하시는 모든 분들은 쿠알로아랜치에서 메일로 발송드린 <span style="color: rgb(239, 68, 68);"><strong>면책 동의서 제출</strong></span>하셔야 참여 가능합니다. (미제출 시 투어 참여, 환불 불가) Kualoa Ranch 이름으로 발송된 메일 확인 부탁드리며, 스팸함도 함께 확인해보시기 바랍니다.</p></li><li><p>개인 부주의 또는 무모한 운전으로 인해 랩터, 장비에 손상이 발생할 경우 보상 비용이 별도 청구될 수 있습니다.</p></li><li><p>본 투어는 차량의 흔들림(진동)이 심할 수 있습니다. 오프로드를 달리는 투어로 신체에 기존 또는 반복적인 불편이 있으신 분에겐 권장드리지 않으며 임산부는 참여 불가합니다.</p></li><li><p>만 5세 이상부터 탑승 가능하며, 만 17세 이하는 성인 보호자와 항상 동반해야 합니다.</p></li><li><p>투어 요건을 충족하지 못하실 경우 투어에 참여하실 수 없으며 환불이나 일정 변경 불가능 합니다.</p></li><li><p>현지 사정으로 인해 투어 일정이 예고없이 변경되거나 취소될 수 있습니다.</p></li></ul><p></p>'
};

export const KUALOA_RANCH_UTV_RAPTOR_ADVENTURE_PICKUP = {
  arrival_location:
    '<p>SHERATON WAIKIKI 호텔 - ALOHA LANDING (알로하 랜딩)</p><p><span class="node-image"><span class="image-component"><img src="https://hpwrnhxgnawyfmhwqqsm.supabase.co/storage/v1/object/public/location-images/reservations/20260529-JH001/location/37c83481-8a80-428d-8e74-e80598b26f43.jpg" alt="SHERATON WAIKIKI 호텔 - ALOHA LANDING (알로하 랜딩) 1.jpg" title="" width="265.7569580078125" height="181.45709924783793" style="max-width: 265.7569580078125px" data-keep-ratio="true" class=""></span></span></p><ul><li><p>차량에 Fly shuttle 또는 Kualoa Ranch 라고 적혀있습니다.</p></li><li><p>셔틀 탑승 후 쿠알로아랜치 직원이 버스 티켓을 드립니다.해당 티켓 잘 지참하셨다가 <strong>호텔 복귀 셔틀 탑승 시 제출</strong>하셔야 셔틀 탑승 가능합니다. 복귀 셔틀 탑승 장소와 시간은 쿠알로아랜치 하차 시 직원이 안내드립니다.</p></li><li><p>셔틀 탑승 후 쿠알로아랜치 직원이 체크인 해드립니다. 간혹 쿠알로아랜치 직원의 실수로 체크인이 누락되는 경우가 있어 <span style="color: rgb(59, 130, 246);"><strong>투어 45분 전까지티켓오피스(매표소)</strong></span>에 가셔서 바우처 제시하시고 체크인 잘 되어 있는지 확인하시기 바랍니다. 정상적으로 체크인 되어 있을 경우 투어 장소로 이동하시면 됩니다.</p></li></ul>',
  delivery_notes:
    '<ul><li><p>투어 참여하시는 <strong>모든 분들은 쿠알로아랜치에서 제공하는 위 링크 </strong><span style="color: rgb(239, 68, 68);"><strong>면책 동의서 제출</strong></span>하셔야 참여 가능합니다.</p></li><li><p>위 링크 전체를 복사하여 인터넷 창에 붙여넣기 하신 후 \'Sign waivers\'를 클릭하시고 모든 인원의 정보를 기입하시면 됩니다.</p></li><li><p>동의서는 미리 등록하셔도 되고, 늦어도 체크인 하시기 전까지 제출하셔야 합니다.<span style="color: rgb(239, 68, 68);"> <strong>(미제출 시 투어 참여, 환불 불가)</strong></span></p></li></ul>',
  guide_notes:
    '<ul><li><p>본 바우처를 출력 또는 캡쳐하여 가져가시기 바랍니다. 바우처 미 지참시 진행이 불가합니다.</p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>준비물 : 바우처(캡처본), 대표 예약자의 여권(지참 또는 사진촬영본 가능), UTV 운전자분의 국제운전면허증 실물 지참</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>바우처와 여권은 예약자명과 일치하여야 하며 여권은 본인 확인을 위해 사진이 있는 전체 페이지를 제시해주셔야 합니다.</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>UTV 운전자는 만 21세 이상이여야 하며, 운전자 명의 국제운전면허증 지참하셔야 합니다. 준비물 미지참 시 투어 참여 불가하며, 전액 환불 불가합니다.</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>투어 참여에 적절한 편안한 복장 &amp; 운동화 착용과 햇빛(자외선)이 강할 수 있어 필요 시 썬글라스와 썬크림 지참 권장드립니다.</strong></span></p></li><li><p>셔틀시간 보다 10분 일찍 픽업장소에서 대기하여 주시기 바랍니다.</p></li><li><p>셔틀시간이 5분 정도 지연될 경우 픽업장소를 이탈하지 마시고, 조인하와이 현지 연락처로 연락주시기 바랍니다. 시간 지연 시 연락을 주시지 않아 픽업이 안되었을 경우 취소 및 환불이 불가합니다.</p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>투어 종료 후 쿠알로아에서 약 " "PM 출발입니다. (미리 셔틀 탑승 장소에서 대기하시기 바랍니다.)</strong></span></p></li><li><p>투어 참여하시는 모든 분들은 쿠알로아랜치에서 메일로 발송드린 <span style="color: rgb(239, 68, 68);"><strong>면책 동의서를 제출</strong></span>하셔야 참여 가능합니다. (미제출 시 투어 참여, 환불 불가) Kualoa Ranch 이름으로 발송된 메일 확인 부탁드리며, 스팸함도 함께 확인해보시기 바랍니다.</p></li><li><p>시간 불이행으로 인한 행사 불참 시 별도의 연락없이 진행되며 전액 환불 불가합니다.</p></li><li><p>개인 부주의로 인해 랩터, 장비에 손상이 발생할 경우 보상 비용이 별도 청구될 수 있습니다.</p></li><li><p>본 투어는 차량의 흔들림(진동)이 심할 수 있습니다. 오프로드를 달리는 투어로 신체에 기존 또는 반복적인 불편이 있으신 분에겐 권장드리지 않으며 임산부는 참여 불가합니다.</p></li><li><p>만 5세 이상부터 탑승 가능하며, 만 17세 이하는 성인 보호자와 항상 동반해야 합니다.</p></li><li><p>투어 요건을 충족하지 못하실 경우 투어에 참여하실 수 없으며 환불이나 일정 변경 불가능 합니다.</p></li><li><p>현지 사정으로 인해 투어 일정이 예고없이 변경되거나 취소될 수 있습니다.</p></li></ul>'
};

export const KUALOA_RANCH_UTV_RIDE_ALONG_ADVENTURE_NO_PICKUP = {
  arrival_location:
    '<p><strong>쿠알로아 랜치 </strong><span style="color: rgb(59, 130, 246);"><strong>티켓 오피스</strong></span><strong>에 가셔서 </strong><span style="color: rgb(59, 130, 246);"><strong>바우처와 여권 제시</strong></span><strong> 부탁드립니다.</strong></p><p></p><p>티켓 오피스에서 체크인 하시고 인쇄 탑승권 또는 모바일 탑승권을 수령하신 후 안내받으신 투어 장소로 이동하시면 됩니다.</p><p>투어 장소에 있는 <strong>가이드에게</strong> 다시 한 번 <strong>체크인</strong> 하시면 됩니다.</p><p></p><p><strong>[GPS, 구글 지도 입력] Kualoa Ranch Ticket Office</strong></p><p><strong>[Kualoa Ranch 주소] 49-560 Kamehameha Hwy, Kaneohe, HI 96744</strong></p>',
  delivery_notes:
    '<ul><li><p>투어 참여하시는 <strong>모든 분들은 쿠알로아랜치에서 제공하는 위 링크 </strong><span style="color: rgb(239, 68, 68);"><strong>면책 동의서 제출</strong></span>하셔야 참여 가능합니다.</p></li><li><p>위 링크 전체를 복사하여 인터넷 창에 붙여넣기 하신 후 \'Sign waivers\'를 클릭하시고 모든 인원의 정보를 기입하시면 됩니다.</p></li><li><p>동의서는 미리 등록하셔도 되고, 늦어도 체크인 하시기 전까지 제출하셔야 합니다.<span style="color: rgb(239, 68, 68);"> <strong>(미제출 시 투어 참여, 환불 불가)</strong></span></p></li></ul>',
  guide_notes:
    '<ul><li><p>본 바우처를 출력 또는 캡쳐하여 가져가시기 바랍니다. 바우처 미 지참시 진행이 불가합니다.</p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>준비물 : 바우처(캡처본), 대표 예약자의 여권(지참 또는 사진촬영본 가능)</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>바우처와 여권은 예약자명과 일치하여야 하며 여권은 본인 확인을 위해 사진이 있는 전체 페이지를 제시해주셔야 합니다.</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>UTV 운전자는 만 21세 이상이여야 하며, 운전자 명의 국제운전면허증 지참하셔야 합니다. 준비물 미지참 시 투어 참여 불가하며, 전액 환불 불가합니다.</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>투어 참여에 적절한 편안한 복장 &amp; 운동화 착용과 햇빛(자외선)이 강할 수 있어 필요 시 썬글라스와 썬크림 지참 권장드립니다.</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>위에 기재된 체크인 시간에 늦지 않게 도착하시기 바랍니다. (쿠알로아랜치 규정 상 프로그램 시간 45분 전까지 체크인 하셔야 합니다.) </strong></span>투어 당일 렌터카 픽업하시는 분들께선 렌터카 픽업이 지연될 경우 쿠알로아 체크인 시간까지 도착 못하실 수 있습니다. 체크인 시간 불이행으로 인한 행사 불참 시 별도의 연락없이 진행되며 전액 환불 불가합니다.</p></li><li><p>투어 참여하시는 모든 분들은 쿠알로아랜치에서 메일로 발송드린 <span style="color: rgb(239, 68, 68);"><strong>면책 동의서를 제출</strong></span>하셔야 참여 가능합니다. (미제출 시 투어 참여, 환불 불가) Kualoa Ranch 이름으로 발송된 메일 확인 부탁드리며, 스팸함도 함께 확인해보시기 바랍니다.</p></li><li><p>본 투어는 차량의 흔들림(진동)이 심할 수 있습니다. 오프로드를 달리는 투어로 신체에 기존 또는 반복적인 불편이 있으신 분에겐 권장드리지 않으며 임산부는 참여 불가합니다.</p></li><li><p>만 5세 이상부터 탑승 가능하며, 만 17세 이하는 성인 보호자와 항상 동반해야 합니다.</p></li><li><p>투어 요건을 충족하지 못하실 경우 투어에 참여하실 수 없으며 환불이나 일정 변경 불가능 합니다.</p></li><li><p>현지 사정으로 인해 투어 일정이 예고없이 변경되거나 취소될 수 있습니다.</p></li></ul>'
};

export const KUALOA_RANCH_UTV_RIDE_ALONG_ADVENTURE_PICKUP = {
  arrival_location:
    '<p>SHERATON WAIKIKI 호텔 - ALOHA LANDING (알로하 랜딩)</p><p><span class="node-image"><span class="image-component"><img src="https://hpwrnhxgnawyfmhwqqsm.supabase.co/storage/v1/object/public/location-images/reservations/20260529-JH001/location/37c83481-8a80-428d-8e74-e80598b26f43.jpg" alt="SHERATON WAIKIKI 호텔 - ALOHA LANDING (알로하 랜딩) 1.jpg" title="" width="265.7569580078125" height="181.45709924783793" style="max-width: 265.7569580078125px" data-keep-ratio="true" class=""></span></span></p><ul><li><p>차량에 Fly shuttle 또는 Kualoa Ranch 라고 적혀있습니다.</p></li><li><p>셔틀 탑승 후 쿠알로아랜치 직원이 버스 티켓을 드립니다.해당 티켓 잘 지참하셨다가 <strong>호텔 복귀 셔틀 탑승 시 제출</strong>하셔야 셔틀 탑승 가능합니다. 복귀 셔틀 탑승 장소와 시간은 쿠알로아랜치 하차 시 직원이 안내드립니다.</p></li><li><p>셔틀 탑승 후 쿠알로아랜치 직원이 체크인 해드립니다. 간혹 쿠알로아랜치 직원의 실수로 체크인이 누락되는 경우가 있어 <span style="color: rgb(59, 130, 246);"><strong>투어 45분 전까지티켓오피스(매표소)</strong></span>에 가셔서 바우처 제시하시고 체크인 잘 되어 있는지 확인하시기 바랍니다. 정상적으로 체크인 되어 있을 경우 투어 장소로 이동하시면 됩니다.</p></li></ul>',
  delivery_notes:
    '<ul><li><p>투어 참여하시는 <strong>모든 분들은 쿠알로아랜치에서 제공하는 위 링크 </strong><span style="color: rgb(239, 68, 68);"><strong>면책 동의서 제출</strong></span>하셔야 참여 가능합니다.</p></li><li><p>위 링크 전체를 복사하여 인터넷 창에 붙여넣기 하신 후 \'Sign waivers\'를 클릭하시고 모든 인원의 정보를 기입하시면 됩니다.</p></li><li><p>동의서는 미리 등록하셔도 되고, 늦어도 체크인 하시기 전까지 제출하셔야 합니다.<span style="color: rgb(239, 68, 68);"> <strong>(미제출 시 투어 참여, 환불 불가)</strong></span></p></li></ul>',
  guide_notes:
    '<ul><li><p>본 바우처를 출력 또는 캡쳐하여 가져가시기 바랍니다. 바우처 미 지참시 진행이 불가합니다.</p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>준비물 : 바우처(캡처본), 대표 예약자의 여권(지참 또는 사진촬영본 가능)</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>바우처와 여권은 예약자명과 일치하여야 하며 여권은 본인 확인을 위해 사진이 있는 전체 페이지를 제시해주셔야 합니다. 준비물 미지참 시 투어 참여 불가하며, 전액 환불 불가합니다.</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>투어 참여에 적절한 편안한 복장 &amp; 운동화 착용과 햇빛(자외선)이 강할 수 있어 필요 시 썬글라스와 썬크림 지참 권장드립니다.</strong></span></p></li><li><p>셔틀시간 보다 10분 일찍 픽업장소에서 대기하여 주시기 바랍니다.</p></li><li><p>셔틀시간이 5분 정도 지연될 경우 픽업장소를 이탈하지 마시고, 조인하와이 현지 연락처로 연락주시기 바랍니다. 시간 지연 시 연락을 주시지 않아 픽업이 안되었을 경우 취소 및 환불이 불가합니다.</p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>투어 종료 후 쿠알로아에서 약 " "PM 출발입니다. (미리 셔틀 탑승 장소에서 대기하시기 바랍니다.)</strong></span></p></li><li><p>투어 참여하시는 모든 분들은 쿠알로아랜치에서 메일로 발송드린 <span style="color: rgb(239, 68, 68);"><strong>면책 동의서를 제출</strong></span>하셔야 참여 가능합니다. (미제출 시 투어 참여, 환불 불가) Kualoa Ranch 이름으로 발송된 메일 확인 부탁드리며, 스팸함도 함께 확인해보시기 바랍니다.</p></li><li><p>시간 불이행으로 인한 행사 불참 시 별도의 연락없이 진행되며 전액 환불 불가합니다.</p></li><li><p>개인 부주의로 인해 랩터, 장비에 손상이 발생할 경우 보상 비용이 별도 청구될 수 있습니다.</p></li><li><p>본 투어는 차량의 흔들림(진동)이 심할 수 있습니다. 오프로드를 달리는 투어로 신체에 기존 또는 반복적인 불편이 있으신 분에겐 권장드리지 않으며 임산부는 참여 불가합니다.</p></li><li><p>만 5세 이상부터 탑승 가능하며, 만 17세 이하는 성인 보호자와 항상 동반해야 합니다.</p></li><li><p>투어 요건을 충족하지 못하실 경우 투어에 참여하실 수 없으며 환불이나 일정 변경 불가능 합니다.</p></li><li><p>현지 사정으로 인해 투어 일정이 예고없이 변경되거나 취소될 수 있습니다.</p></li></ul>'
};

export const KUALOA_RANCH_ELECTRIC_MOUNTAIN_BIKE_TOUR_NO_PICKUP = {
  arrival_location:
    '<p><strong>쿠알로아 랜치 </strong><span style="color: rgb(59, 130, 246);"><strong>티켓 오피스</strong></span><strong>에 가셔서 </strong><span style="color: rgb(59, 130, 246);"><strong>바우처와 여권 제시</strong></span><strong> 부탁드립니다.</strong></p><p></p><p>티켓 오피스에서 체크인 하시고 인쇄 탑승권 또는 모바일 탑승권을 수령하신 후 안내받으신 투어 장소로 이동하시면 됩니다.</p><p>투어 장소에 있는 <strong>가이드에게</strong> 다시 한 번 <strong>체크인</strong> 하시면 됩니다.</p><p></p><p><strong>[GPS, 구글 지도 입력] Kualoa Ranch Ticket Office</strong></p><p><strong>[Kualoa Ranch 주소] 49-560 Kamehameha Hwy, Kaneohe, HI 96744</strong></p>',
  delivery_notes:
    '<ul><li><p>투어 참여하시는 <strong>모든 분들은 쿠알로아랜치에서 제공하는 위 링크 </strong><span style="color: rgb(239, 68, 68);"><strong>면책 동의서 제출</strong></span>하셔야 참여 가능합니다.</p></li><li><p>위 링크 전체를 복사하여 인터넷 창에 붙여넣기 하신 후 \'Sign waivers\'를 클릭하시고 모든 인원의 정보를 기입하시면 됩니다.</p></li><li><p>동의서는 미리 등록하셔도 되고, 늦어도 체크인 하시기 전까지 제출하셔야 합니다.<span style="color: rgb(239, 68, 68);"> <strong>(미제출 시 투어 참여, 환불 불가)</strong></span></p></li></ul>',
  guide_notes:
    '<ul><li><p>본 바우처를 출력 또는 캡쳐하여 가져가시기 바랍니다. 바우처 미 지참시 진행이 불가합니다.</p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>준비물 : 바우처(캡처본), 대표 예약자의 여권(지참 또는 사진촬영본 가능), 발 전체 덮는 운동화 필수 착용</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>바우처와 여권은 예약자명과 일치하여야 하며 여권은 본인 확인을 위해 사진이 있는 전체 페이지를 제시해주셔야 합니다. 준비물 미지참, 미착용 시 투어 참여 불가하며, 전액 환불 불가합니다.</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>투어 참여에 적절한 편안한 복장 &amp; 운동화 착용과 햇빛(자외선)이 강할 수 있어 필요 시 썬글라스와 썬크림 지참 권장드립니다.</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>위에 기재된 체크인 시간에 늦지 않게 도착하시기 바랍니다. (쿠알로아랜치 규정 상 프로그램 시간 45분 전까지 체크인 하셔야 합니다.)</strong></span> 투어 당일 렌터카 픽업하시는 분들께선 렌터카 픽업이 지연될 경우 쿠알로아 체크인 시간까지 도착 못하실 수 있습니다. 체크인 시간 불이행으로 인한 행사 불참 시 별도의 연락없이 진행되며 전액 환불 불가합니다.</p></li><li><p>투어 참여하시는 모든 분들은 쿠알로아랜치에서 메일로 발송드린 <span style="color: rgb(239, 68, 68);"><strong>면책 동의서를 제출</strong></span>하셔야 참여 가능합니다. (미제출 시 투어 참여, 환불 불가) Kualoa Ranch 이름으로 발송된 메일 확인 부탁드리며, 스팸함도 함께 확인해보시기 바랍니다.</p></li><li><p>개인 부주의 또는 무모한 운전으로 인해 자전거, 장비에 손상이 발생할 경우 보상 비용이 별도 청구될 수 있습니다.</p></li><li><p>오프로드를 달리는 투어로 신체에 기존 또는 반복적인 불편이 있으신 분과 임산부에겐 권장드리지 않습니다.</p></li><li><p>바우처에 기재된 장소를 모르실 경우 현지 조인하와이로 문의하여 안내 받으시기 바랍니다.</p></li><li><p>자전거를 탈 줄 아셔야하며 운전이 미숙할 경우 직원 판단하에 투어 참여 불가할 수 있습니다. (해당 사유로는 환불도 불가합니다.)</p></li><li><p>투어 요건을 충족하지 못하실 경우 투어에 참여하실 수 없으며 환불이나 일정 변경 불가능 합니다.</p></li><li><p>현지 사정으로 인해 투어 일정이 예고없이 변경되거나 취소될 수 있습니다.</p></li></ul>'
};

export const KUALOA_RANCH_ELECTRIC_MOUNTAIN_BIKE_TOUR_PICKUP = {
  arrival_location:
    '<p>SHERATON WAIKIKI 호텔 - ALOHA LANDING (알로하 랜딩)</p><p><span class="node-image"><span class="image-component"><img src="https://hpwrnhxgnawyfmhwqqsm.supabase.co/storage/v1/object/public/location-images/reservations/20260529-JH001/location/37c83481-8a80-428d-8e74-e80598b26f43.jpg" alt="SHERATON WAIKIKI 호텔 - ALOHA LANDING (알로하 랜딩) 1.jpg" title="" width="265.7569580078125" height="181.45709924783793" style="max-width: 265.7569580078125px" data-keep-ratio="true" class=""></span></span></p><ul><li><p>차량에 Fly shuttle 또는 Kualoa Ranch 라고 적혀있습니다.</p></li><li><p>셔틀 탑승 후 쿠알로아랜치 직원이 버스 티켓을 드립니다.해당 티켓 잘 지참하셨다가 <strong>호텔 복귀 셔틀 탑승 시 제출</strong>하셔야 셔틀 탑승 가능합니다. 복귀 셔틀 탑승 장소와 시간은 쿠알로아랜치 하차 시 직원이 안내드립니다.</p></li><li><p>셔틀 탑승 후 쿠알로아랜치 직원이 체크인 해드립니다. 간혹 쿠알로아랜치 직원의 실수로 체크인이 누락되는 경우가 있어 <span style="color: rgb(59, 130, 246);"><strong>투어 45분 전까지티켓오피스(매표소)</strong></span>에 가셔서 바우처 제시하시고 체크인 잘 되어 있는지 확인하시기 바랍니다. 정상적으로 체크인 되어 있을 경우 투어 장소로 이동하시면 됩니다.</p></li></ul>',
  delivery_notes:
    '<ul><li><p>투어 참여하시는 <strong>모든 분들은 쿠알로아랜치에서 제공하는 위 링크 </strong><span style="color: rgb(239, 68, 68);"><strong>면책 동의서 제출</strong></span>하셔야 참여 가능합니다.</p></li><li><p>위 링크 전체를 복사하여 인터넷 창에 붙여넣기 하신 후 \'Sign waivers\'를 클릭하시고 모든 인원의 정보를 기입하시면 됩니다.</p></li><li><p>동의서는 미리 등록하셔도 되고, 늦어도 체크인 하시기 전까지 제출하셔야 합니다.<span style="color: rgb(239, 68, 68);"> <strong>(미제출 시 투어 참여, 환불 불가)</strong></span></p></li></ul>',
  guide_notes:
    '<ul><li><p>본 바우처를 출력 또는 캡쳐하여 가져가시기 바랍니다. 바우처 미 지참시 진행이 불가합니다.</p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>준비물 : 바우처(캡처본), 대표 예약자의 여권(지참 또는 사진촬영본 가능), 발 전체 덮는 운동화 필수 착용</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>바우처와 여권은 예약자명과 일치하여야 하며 여권은 본인 확인을 위해 사진이 있는 전체 페이지를 제시해주셔야 합니다. 준비물 미지참, 미착용 시 투어 참여 불가하며, 전액 환불 불가합니다.</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>투어 참여에 적절한 편안한 복장 &amp; 운동화 착용과 햇빛(자외선)이 강할 수 있어 필요 시 썬글라스와 썬크림 지참 권장드립니다.</strong></span></p></li><li><p>셔틀시간 보다 10분 일찍 픽업장소에서 대기하여 주시기 바랍니다.</p></li><li><p>셔틀시간이 5분 정도 지연될 경우 픽업장소를 이탈하지 마시고, 조인하와이 현지 연락처로 연락주시기 바랍니다. 시간 지연 시 연락을 주시지 않아 픽업이 안되었을 경우 취소 및 환불이 불가합니다.</p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>투어 종료 후 쿠알로아에서 약 " "PM 출발입니다. (미리 셔틀 탑승 장소에서 대기하시기 바랍니다.)</strong></span></p></li><li><p>투어 참여하시는 모든 분들은 쿠알로아랜치에서 메일로 발송드린 <span style="color: rgb(239, 68, 68);"><strong>면책 동의서를 제출</strong></span>하셔야 참여 가능합니다. (미제출 시 투어 참여, 환불 불가) Kualoa Ranch 이름으로 발송된 메일 확인 부탁드리며, 스팸함도 함께 확인해보시기 바랍니다.</p></li><li><p>시간 불이행으로 인한 행사 불참 시 별도의 연락없이 진행되며 전액 환불 불가합니다.</p></li><li><p>개인 부주의 또는 무모한 운전으로 인해 자전거, 장비에 손상이 발생할 경우 보상 비용이 별도 청구될 수 있습니다.</p></li><li><p>오프로드를 달리는 투어로 신체에 기존 또는 반복적인 불편이 있으신 분과 임산부에겐 권장드리지 않습니다.</p></li><li><p>바우처에 기재된 장소를 모르실 경우 현지 조인하와이로 문의하여 안내 받으시기 바랍니다.</p></li><li><p>자전거를 탈 줄 아셔야하며 운전이 미숙할 경우 직원 판단하에 투어 참여 불가할 수 있습니다. (해당 사유로는 환불도 불가합니다.)</p></li><li><p>투어 요건을 충족하지 못하실 경우 투어에 참여하실 수 없으며 환불이나 일정 변경 불가능 합니다.</p></li><li><p>현지 사정으로 인해 투어 일정이 예고없이 변경되거나 취소될 수 있습니다.</p></li></ul>'
};

export const HAWAII_SURFING = {
  arrival_location:
    '<p>H&amp;M 매장 옆 쪽 (SEASIDE AVE 쪽) 트롤리 버스 정류장에서 진행됩니다.</p><p><span class="node-image"><span class="image-component"><img src="https://hpwrnhxgnawyfmhwqqsm.supabase.co/storage/v1/object/public/location-images/reservations/20260721-JH001/location/d7476cca-deea-46ca-ac04-dc6c893aa5fb.png" alt="20260721_120821.png" title="" width="null" height="null" style="max-width: nullpx" data-keep-ratio="true" class=""></span></span></p>',
  guide_notes:
    '<ul><li><p><span style="color: rgb(59, 130, 246);"><strong>본 바우처를 캡쳐 또는 출력하셔서 지참 해주셔야 참여 가능합니다.</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>수영복(옷 안에 미리 착용), 선크림, 수건 등 개인 용품을 준비하여 주시기 바랍니다.</strong></span></p></li><li><p>비치에 설치되어 있는 간이 샤워시설에서 물로만 샤워 가능합니다. (비누, 샴푸 등 사용 불가)</p></li><li><p>포함사항 : 왕복 교통편, 음료 (물, 커피, 주스)</p></li><li><p>불포함 사항 : $10/인 현장 지불 시 개수에 상관없이 대여 (래쉬가드, 웻슈트, 아쿠아슈즈, 구명조끼, 레깅스(여성용))</p></li><li><p>픽업시간 보다 10분 일찍 픽업장소에서 대기하여 주시기 바랍니다.</p></li><li><p>픽업시간이 5분 정도 지연될 경우 픽업장소를 이탈하지 마시고, 조인하와이 현지 연락처로 연락주시기 바랍니다. 픽업시간 지연 시 연락을 주시지 않아 픽업이 안되었을 경우 취소 및 환불이 불가합니다.</p></li><li><p>픽업시간 불이행으로 인한 행사 불참 시에는 별도의 연락은 드리지 않으며, 전액 환불 불가합니다.</p></li><li><p>도난의 위험이 있으므로 최소한의 짐만 지참 부탁드리며 귀중품은 숙소에 두고 오시기 바랍니다.</p></li><li><p>현지사정에 의해 일정은 예고없이 변경/취소될 수 있습니다.</p></li></ul><p></p>'
};

export const KANEOHE_SANDBAR_ADVENTURE = {
  arrival_location:
    '<p>SHERATON WAIKIKI 호텔 - 고객 전용 주차장 건물 입구 Donho Lane (돈호레인)</p><p><span class="node-image"><span class="image-component"><img src="https://hpwrnhxgnawyfmhwqqsm.supabase.co/storage/v1/object/public/location-images/reservations/20260529-JH001/location/e0f80ccb-6c1c-432e-a4e9-f613d2c002da.jpg" alt="SHERATON WAIKIKI 호텔 - 고객 전용 주차장 건물 입구 Donho Lane (돈호레인) 1.jpg" title="" width="368.34722900390625" height="227.03808496021693" style="max-width: 368.34722900390625px" data-keep-ratio="true" class=""></span></span></p>',
  guide_notes:
    '<ul><li><p>본 바우처를 출력 또는 캡쳐하여 가져가시기 바랍니다. 바우처 미 지참시 진행이 불가합니다.</p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>수영복(옷 안에 미리 착용), 래쉬가드, 아쿠아슈즈, 비치타올, 선크림, 여벌 옷 등 개인물품을 준비하여 주시기 바랍니다.</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>팁 불포함이므로 $10/인 현금으로 사전 준비하셔서 투어 당일 드라이버에게 현장 지불하셔야 합니다.</strong></span></p></li><li><p>픽업시간 보다 5분 일찍 픽업장소에서 대기하여 주시기 바랍니다.</p></li><li><p>픽업시간이 5분 정도 지연될 경우 픽업장소를 이탈하지 마시고, 조인하와이 현지 데스크로 연락주시기 바랍니다. 픽업시간 지연 시 연락을 주시지 않아 픽업이 안되었을 경우 취소 및 환불이 불가합니다.</p></li><li><p>픽업시간 불이행으로 인한 행사 불참 시에는 별도의 연락은 드리지 않으며, 전액 환불 불가합니다.</p></li></ul>'
};

export const HAWAII_SNAP = {
  arrival_location:
    '<p><strong>Honolulu Police Department Waikiki Station 경찰서 앞</strong></p><p>- 주소 2425 Kalākaua Ave, Honolulu</p><p><span class="node-image"><span class="image-component"><img src="https://hpwrnhxgnawyfmhwqqsm.supabase.co/storage/v1/object/public/location-images/reservations/20260529-JH001/location/f5037a9b-bb52-44cc-a4f9-a2e28c1ba07a.jpg" alt="Honolulu Police Department Waikiki Station 경찰서 앞 - 주소 2425 Kalākaua Ave, Honolulu.jpg" title="" width="335.1423645019531" height="139.4340362548828" style="max-width: 335.1423645019531px" data-keep-ratio="true" class=""></span></span></p>',
  guide_notes:
    '<ul><li><p><span style="color: rgb(59, 130, 246);"><strong>본 바우처 출력 또는 핸드폰 캡쳐본으로 제시 부탁드립니다.</strong></span></p></li><li><p>촬영 작가님 팁 포함입니다.</p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>촬영 진행시 시간상 환복이 불가합니다.</strong></span></p></li><li><p><span style="color: rgb(59, 130, 246);"><strong>검은색(어두운 색) 착용은 권장드리지 않습니다.</strong></span></p></li><li><p>시간 불이행으로 인한 행사 불참 시 별도의 연락없이 진행되며 전액 환불 불가합니다.</p></li><li><p>미팅시간 5분이 지나도 작가님 못만나셨을 경우 장소를 이탈하지 마시고, 조인하와이 현지 연락처로 연락주시기 바랍니다. 연락을 주시지 않아 진행이 안되었을 경우 취소 및 환불이 불가합니다.</p></li><li><p>바우처에 기재된 장소를 모르실 경우 현지 조인하와이로 문의하여 안내 받으시기 바랍니다.</p></li></ul><p></p>'
};
